
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

categories:
- digital-nomad
- travel
- hotspots

_inputs:
  textarea_html:
    options:
      blockquote: true
      bold: true
      format: p h1 h2 h3 h4 h5 h6
      italic: true
      strike: true
      underline: true 
      bulletedlist: true
      numberedlist: true
      horizontalrule: true
      image: true
      undo: true
      redo: true

page_blocks: []
_array_structures:
  content-blocks:
    values:
      - label: Hero
        icon: star
        value: 
          _section-type: hero
          image: 
          textarea_html: