collections:
  posts:
    output: true
    permalink: /post/:title

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

categories:
- digital-nomad
- travel
- hotspots

_inputs:
  textarea_html:
    options:
      options:
      blockquote: true
      bold: true
      format: p h1 h2 h3 h4 h5 h6
      italic: true
      strike: true
      underline: true 
      link: true
      bulletedlist: true
      numberedlist: true
      horizontalrule: true
      styles: /custom-styles.css
      left: left
      center: center
      right: right
      justify: justify
      image: true
      undo: true
      redo: true

page_blocks: []
_array_structures:
  content-blocks:
    values:
      - label: One Image grid
        icon: image
        value: 
          _section-type: 1-image-block
          1_image: /images/mission.jpg
          content-block-link:
      - label: Wide Image
        icon: image
        value: 
          _section-type: wide-image
          1_image: /images/mission.jpg
          content-block-link:
      - label: two image grid
        icon: photo_library
        value: 
          _section-type: 2-image-block
          1_image: /images/mission.jpg
          2_image: /images/mission.jpg
          content-block-link:
      - label: All Blogs 
        icon: edit_note
        value: 
          _section-type: all-blogs
          heading: Explore our blogs
      - label: Blog Article
        icon: edit_note
        value:
          _section-type: blog-article
          textarea_html: Add block of text here
          colors: 
            background-color:
            text-color:
            heading-color:
            subheading-color:
          fonts:
            text-font:
            heading-font:
            subheading-font:
      - label: Blog Category Introduction Section
        icon: article
        value:
          _section-type: blog-cat-intro
          heading: Travel Blogs
          textarea_html: An introduction on your blogs
          image: /images/mission.jpg
          sub-heading: Hot Topics
          content-block-link:
      - label: Button in the center
        icon: smart_button
        value:
          _section-type: button-center
          cta-link: /contact-us
          cta: Inquire
          background-image:
          background-color: '#FFFFFF'
          content-block-link:
      - label: Button on the right
        icon: smart_button
        value:
          _section-type: button-right
          background_image: /images/side-button.webp 
          background-color:
          cta: Inquire 
          cta-link: /work-with-us
          content-block-link:
      - label: Digital Nomad Blogs
        icon: article
        value:
          _section-type: digital-nomad-blogs
          heading: Digital Nomad Blogs
          content-block-link:
      - label: Contact Form
        icon: assignment
        value:
          _section-type: form  
          heading: Contact Us
          textarea_html: <h4>Let's Connect!</h4><p>You can mail directly to hello@trendytravelduo.com or fill the contact form below.</p>
          image: /images/contact.webp 
          form: 
            label-1: Name
            label-2: Email
            label-3: Subject
            label-4: Message
            button: Submit
          content-block-link:
      - label: Gallery
        icon: grid_on
        value:
          _section-type: gallery
          background-color: '#FFFFFF'
          textarea_html: <p>Hotels</p>
          1_image: /images/work-with-us-1.webp
          2_image: /images/placeholder-1.jpg
          3_image: /images/work-with-us-2.webp
          4_image: /images/placeholder-2.jpg
          5_image: /images/work-with-us-3.webp
          6_image: /images/placeholder-3.jpg
          content-block-link:
      - label: Hero
        icon: star
        value: 
          _section-type: hero
          background_image: /images/homepage/Oman-00472-3.webp
          heading: TRENDY TRAVEL
          subheading: CREATIVE AGENCY
          content-block-link:
      - label: Hotspots Blogs
        icon: article
        value:
          _section-type: hotspots-blog
          heading: Hotspots blogs
          content-block-link:
      - label: Instagram Grid
        icon: face_retouching_natural
        value:
          _section-type: instagram-grid
          heading: Follow our adventure!
          cta: Follow on instagram
          background-color: '#F5F0EB'
          content-block-link:
      - label: Jump to Link
        icon: add_link
        value:
          _section-type: jump-to-link
          heading: Work With Us
          textarea_html: >-
            <p>Hi, nice to (digitally) meet you! We are Roel and Eline, also known as Trendy Travel Duo on social media. We are a photo- and videographer couple who make content showcasing luxury hotels, products, and experiences around the world.</p><p>We don’t hesitate to set our alarm at 4AM to climb a mountain, swim in an ice cold pool or even shoot in a tropical storm and risk our equipment to get that perfect shot for you (true story)!</p> <p>Do you want high quality content for your business to post on our personal Instagram or to use on your (booking) websites and social media? Look no further!</p>
          jump-to: 
            button-cta: Inquire 
            button-cta-link: /contact-us
            plain-cta: Jump to Portfolio
            plain-cta-link: /work-with-us#portfolio
          content-block-link:
      - label: Recent Blogs 
        icon: article
        value:
          _section-type: recent-blogs
          heading: latest blogs
          content-block-link:
      - label: Subscribe
        icon: newspaper
        value:
          _section-type: subscribe
          add-script-here:    
      - label: Scroll
        icon: person
        value:
          _section-type: scroll
          heading: What they're saying about us
          scroll:
            textarea_html: <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium exercitationem est, soluta modi quam pariatur placeat vitae voluptate veniam fugit. Eos eligendi eum ut dolorum a, laboriosam quasi modi optio! <br> Name and surname</p>
          content-block-link:
      - label: Space Block
        icon: check_box_outline_blank
        value:
          _section-type: space-block
          background-color: '#EEEEEE'
      - label: Heading with lines
        icon: block
        value:
          _section-type: special-heading 
          background-color: 'white'
          textarea_html: <h3>OUR MISSION</h3>
          content-block-link:
      - label: Centered Text
        icon: format_align_center
        value:
          _section-type: text-center
          heading: We Offer the following services
          textarea_html: >- 
            <ul><li>Content creation: photos and videos</li><li>Exclusive conten creation: drone & underwater footage</li><li>Sponsored contenton our instagram page</li><li>Brand Colalborations</li><li>Press Trips & Marketing Campaigns</li></ul>
          content-block-link:
      - label: Text + Image grid
        icon: auto_awesome
        value:
          _section-type: text-image-grid 
          icon_image: /images/arrow-icon.png
          heading:
            textarea_html: <h1>Work with Us</h1>
          body:
            textarea_html: >- 
              <p> Are you looking for high-quality, unique and memorable content?</p><p> Look no futher!</p><p>We are a photo- and videographer couple, making content showcasing luxury hotels, products, and experiences around the world. Do you want to see our portfolio or read what past clients have to say about us?</p>
            1_image: /images/work-with-us-1.webp 
            2_image: /images/work-with-us-2.webp 
            3_image: /images/work-with-us-3.webp 
            4_image: /images/work-with-us-4.webp 
            5_image: /images/work-with-us-5.webp 
          content-block-link:
      - label: Not your plain Jane
        icon: draw
        value:
          _section-type: not-your-plain-jane
          heading: Work With Us
          textarea_html: >-
            <p>Hi, nice to (digitally) meet you! We are Roel and Eline, also known as Trendy Travel Duo on social media. We are a photo- and videographer couple who make content showcasing luxury hotels, products, and experiences around the world.</p><p>We don’t hesitate to set our alarm at 4AM to climb a mountain, swim in an ice cold pool or even shoot in a tropical storm and risk our equipment to get that perfect shot for you (true story)!</p> <p>Do you want high quality content for your business to post on our personal Instagram or to use on your (booking) websites and social media? Look no further!</p>
      - label: Text on the left
        icon: east
        value:
          _section-type: text-left 
          colors:
            background-color: 'white'
            top-color: 'white'
            bottom-color: '#F5F0EB'
          body: 
            textarea_html: >- 
              <h4><b>As professional photo and videographers,</b></h4><p class="justify">We curate high-quality content exclusively for the luxury segment, aiming not just to meet but exceed expectations. Our unwavering commitment to excellence sets new benchmarks for visual storytelling. Smooth communication is key, prioritizing openness and efficiency in understanding your vision and requirements throughout the entire creative process.</p> <p class="justify">To provide an all-encompassing experience, we can serve as models in our photos and videos, ensuring a seamless integration of our artistic vision with your brand while alleviating the workload for you. Tailoring to your unique needs, we offer bespoke and custom packages to cater to your distinct requirements.</p><p class="justify">Embark on a journey where visual excellence meets unparalleled luxury, capturing your brand's unique story with precision and elegance.</p>
          quote: 
            textarea_html: >-
               <p class = "center">"We are more than photographers and videographers; we are storytellers crafting a visual narrative that captivates, resonates and leaves a lasting impression."</p>
          image: /images/about-us-edited.jpg
          content-block-link:
      - label: Text on the Right
        icon: west
        value:
          _section-type: text-right 
          background-color: '#FFFFFF'
          image: /images/about-us-edited.jpg
          heading: Hi There
          textarea_html: >- 
            <p class = "left"> Hi, nice to (digitally) meet you! We are Roel and Eline, also known as Trendy Travel Duo on social media. We are a photo- and videographer couple who make content showcasing luxury hotels, products, and experiences anywhere in the world. </p><p class = "left">Do you want us to make high quality content for your business to post on our personal Instagram or to use on your (booking) websites and social media? Visit our ‘work with us’ page! </p><p class="left">Since we are traveling foodies it comes to no surprise that we love sharing the best places to eat, to see and to work on our blog. Through our blogs, photography and videography we hope to inspire others to explore everything this beautiful world has to offer. Do you want to see all our recommendations? Visit our Blog!</p><p class = "left"> If you want to get to know us better, give our ‘About us’ page a look!</p>
          cta: About Us
          cta-link: /work-with-us
          content-block-link: about
      - label: Travel Blogs
        icon: article
        value:
          _section-type: travel-blogs
          heading: Explore our travel blogs
          content-block-link:
      - label: Newsletter Script
        icon: forum
        value:
          _section-type: newsletter-script
          heading: Sign up to our newsletter!
          subheading: Join our community and get free guides, exclusive travel tips and more!
          call-to-action-button: Subscribe
          content-block-link: newsletter
          background_image: /images/signup.png
          add-script-here: >- 
            <script type='text/javascript' src='//s3.amazonaws.com/downloads.mailchimp.com/js/mc-validate.js'></script><script type='text/javascript'>(function($) {window.fnames = new Array(); window.ftypes = new Array();fnames[0]='EMAIL';ftypes[0]='email';fnames[1]='FNAME';ftypes[1]='text';fnames[2]='LNAME';ftypes[2]='text';fnames[3]='ADDRESS';ftypes[3]='address';fnames[4]='PHONE';ftypes[4]='phone';fnames[5]='BIRTHDAY';ftypes[5]='birthday';}(jQuery));var $mcj = jQuery.noConflict(true);</script>
      - label: Portfolio 
        icon: photo_library
        value: 
          _section-type: portfolio
          heading: THE INSIDE HOUSE 
          textarea_html: >- 
            Requested: aesthetic Instagram content with full creative freedom
          slideshow: 
            - image: /images/mission.jpg
            - image: /images/about-us.webp
            - image: /images/work-with-us-3.webp
            - image: /images/mission.jpg
            - image: /images/about-us.webp
            - image: /images/work-with-us-3.webp
            - image: /images/mission.jpg
            - image: /images/about-us.webp
            - image: /images/work-with-us-3.webp
      - label: Fancy Three is a crowd
        icon: 
        value: 
          _section-type: 3-is-a-crowd-split-background 
          heading: VIDEO PORTFOLIO
          left-block: 
            image:  /images/homepage/portfolio/Oman-00797.webp
            link: /contact-us
          middle-block: 
            image:  /images/homepage/portfolio/Oman-00338.webp
            link: /contact-us
          right-block: 
            image:  /images/homepage/portfolio/siargao--3.webp
            link: /contact-us
          colors:
            top-color: '#F5F0EB'
            bottom-color: '#fff'
      - label: Three is a Crowed
        icon: 
        value: 
        _section-type: 3-is-a-crowd
        heading: PORTFOLIO
        left-block: 
          subheading: Hospitality
          image:  /images/homepage/portfolio/Oman-00797.webp
          link: /contact-us
        middle-block: 
          subheading: Products
          image:  /images/homepage/portfolio/Oman-00338.webp
          link: /contact-us
        right-block: 
          subheading: Travel
          image:  /images/homepage/portfolio/siargao--3.webp
          link: /contact-us
        content-block-link: portfolio  
      